name: GitHub Pages

on:
  push:
    branches:
    - main
    paths:
    - 'client/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: npm install, build
      run: |
        sed -i '/\/dist/d' .gitignore
        cd client
        npm ci
        npm run build
        touch ./dist/.nojekyll
        echo $SETZEN_WEBAPP_HOST >> ./dist/CNAME
      env:
        SETZEN_WEBSOCKET_URL: ${{secrets.SETZEN_WEBSOCKET_URL}}
        SETZEN_WEBAPP_HOST: ${{secrets.SETZEN_WEBAPP_HOST}}
        SETZEN_CONTACT_EMAIL: ${{secrets.SETZEN_CONTACT_EMAIL}}
        SETZEN_CONTACT_URL: ${{secrets.SETZEN_CONTACT_URL}}
        SETZEN_CONTACT_ISSUES_URL: ${{secrets.SETZEN_CONTACT_ISSUES_URL}}
        SETZEN_CONTACT_PROJECT_URL: ${{secrets.SETZEN_CONTACT_PROJECT_URL}}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./client/dist
        force_orphan: true
